#api配置
domain: localhost
httpport: 8000
appname: Api
#session 过期时间：60 *60 *24 = 86400s 24h
sessionexpired: 86400 
#cookie
cookiekey1: tokenID
cookiekey2: userID
cookiekey3: pro
#默认头像dir
defaulticon: ../icon/default.jpg
#用户每秒访问频率限制
usersecaccesslimit: 1
#ip每分钟访问频率限制
ipsecaccesslimit: 50
#此模块限流
streamlimit: 50000
#请求过期时间
reqtimeout: 10
#请求的channel buffer
reqchannelbuffer: 50000
#读取MQ的goroutine数量
readgoroutinenum: 10
#写入MQ的goroutine数量
writegoroutinenum: 10


#日志配置
log:
    ginlogpath: ../logs/api.log
    ginloglevel: debug
    syslogpath: ../logs/sys.log
    sysloglevel: debug

#redis配置
redis:
    addr:  127.0.0.1:6379
    #最大空闲数
    maxidle: 100
    #最大连接数，0表示无限制
    maxactive: 40960
    #超时时间
    idletimeout: 120
    #秒杀请求队列
    secreqqueue: sec_req_queue
    #秒杀响应队列
    secrespqueue: sec_resp_queue

#etcd配置
etcd:
    addr: 127.0.0.1:2379
    timeout: 5
    #完整路径等于 prefixkey + productkey
    prefixkey: /pace/gin-exm/
    productkey: product

#mysql配置
mysql:
    addr: 127.0.0.1:3306
    user: pace
    pwd: 123
    database: piliVideo
    config:   charset=utf8
