#api配置
domain: localhost
httpport: 8000
appname: Api
#session 过期时间：60 *60 *24 = 86400s 24h
sessionexpired: 86400 
cookiename: sessionID


#日志配置
log:
    ginlogpath: ../logs/api.log
    ginloglevel: debug
    syslogpath: ../logs/sys.log
    sysloglevel: debug

#redis配置
redis:
    addr:  127.0.0.1:6379
    #最大空闲数
    maxidle: 16
    #最大连接数，0表示无限制
    maxactive: 32
    #超时时间
    idletimeout: 120

#etcd配置
etcd:
    addr: 127.0.0.1:2379
    timeout: 5
    #完整路径等于 prefixkey + productkey
    prefixkey: /pace/gin-exm/api/
    productkey: product

#mysql配置
mysql:
    addr: 127.0.0.1:3306
    user: pace
    pwd: 123
    database: piliVideo
    config:   charset=utf8